// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: revoke_refesh_tokens.sql

package database

import (
	"context"
)

const revokeRToken = `-- name: RevokeRToken :exec
UPDATE refresh_tokens
SET updated_at = NOW(), revoked_at = NOW()
WHERE token = $1
`

func (q *Queries) RevokeRToken(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, revokeRToken, token)
	return err
}
