###
# @name users
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "email": "mloneusk@example.com"
}

@userID1 = {{users.response.body.id}}

###
POST  http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Test chirp 1.",
  "user_id": "{{userID1}}"
}

###
# @name users
POST http://localhost:8080/api/users

{
  "email": "dackjorsey@example.com"
}

@userID2 = {{users.response.body.id}}

###
POST  http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "Test chirp 2.",
  "user_id": "{{userID2}}"
}

###
GET  http://localhost:8080/api/chirps


### 
POST http://localhost:8080/admin/reset
